name: Convert SVG to PNG

on:
  push:
    branches:
      - feat/svg-converter

jobs:
  convert-svg-to-png:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install imagemagick
      run: |
        sudo apt-get install imagemagick

    - name: Convert SVGs to PNGs
      run: |
        total_files=$(find ./ -type f -name "*.svg" | wc -l)
        progress=0

        find ./ -type f -name "*.svg" | while IFS= read -r file; do
            progress=$((progress + 1))
            percentage=$((progress * 100 / total_files))
            filled=$((percentage / 2))
            unfilled=$((50 - filled))
            
            printf "\rProgress: [%${filled}s%${unfilled}s] %d%%" "$(printf '#%.0s' $(seq 1 $filled))" "$(printf ' %.0s' $(seq 1 $unfilled))" "$percentage"
            png_file="${file%.svg} 4k.png"
            convert -background none -density 700 "$file" -quality 100 -resize 4000 "$png_file"
        done
        echo

    - name: Commit and Push Converted PNGs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Generate PNGs"
        git push
